kri_spi_x_videotheque:
    resource: "@KriSpiXVideothequeBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:  /login
    defaults: { _controller: KriSpiXUserBundle:Security:login }

login_check:
    pattern:  /login_check
    
logout:
    pattern:  /logout